### ISSUE TITLE
Shelly Plus PlugS firmware 1.2.3 reboots to shelly

### ISSUE THREAD

**Issue by rolflichter** [tasmota/mgos32-to-tasmota32#49]
with shelly firmware 1.2.3 device is rebooting back to shelly firmware.

-------------------------
Prerequisites
⚠️ Needed ⚠️ Update the device to the latest stable firmware (Internet access!!)
_---- DONE. Devices is updating to shelly firmware 1.2.3_

Download the name corresponding zip package for your device (See [release section](https://github.com/tasmota/mgos32-to-tasmota32/releases))
_---- DONE. downloaded mgos32-to-tasmota32-PlusPlugS.zip_

Navigate to Settings > Firmware and drag & drop the convert "zip" in the firmware update area (do NOT update via URL)
Click the Update button
_---- DONE_

Device is updating, finished in 1-2 minutes
If Shelly Web frontend is back after the update, repeat the steps above.
_---- repeated 10 times. still rebooting to shelly firmware._

did the procedure already with Shelly Plus Plug S + firmware 1.1.0 and it had work like described. but no longer with firmware 1.2.3

thx

**Comment by bkbartk** [comment]
I have the same issue,
first tried with f.w. 1.0.7 that didn't work.
I couldn't find a way to find fw. 1.1.0 so despite of the warning updated to 1.2.3 anyway (stupid of me I know)
and nothing happens when updating tasmota.
update takes 10 to 20 minutes, not 1 to 2 as described but then afterwards shelly is still running.
I have the "Shelly Plus Plus S v2" not sure if that is any different from v1

**Comment by Jason2866** [comment]
Try again, issue should be fixed.

**Comment by Jason2866** [comment]
No, the Berry scripts in "Autoconfig" are updated. No change needed in this repo

**Comment by bkbartk** [comment]
Thnx this works really well,
No idea how berry scripts work and when they are loaded but all steps up untill 11 are completed.
and this time it was 1 to 2 minutes as described and not 20 as before.
