### ISSUE TITLE
Older release to flash ESPHome

### ISSUE THREAD

**Issue by TibsD** [tasmota/mgos32-to-tasmota32#56]
I wanted to flash ESPHome on my Shelly Plus 1 but read that you need a Tasmota version before release 12 to do so. Is this correct?

Where can I find these earlier releases?

**Comment by Jason2866** [comment]
There are none, since not working with current releases of Shelly firmware. It is not possible to flash esphome with this tool. Since the convert process migrates to Tasmota safeboot scheme. This step includes replacing the Shelly bootloader. Without doing this at next boot the device will be soft bricked. Only hardware serial can recover.
